spyder-ide/spyder-notebook

spyder_notebook/notebookplugin.py
=> PR: Add '+' button to open new notebooks.

spyder_notebook/notebookplugin.py, spyder_notebook/widgets/client.py, spyder_notebook/widgets/dom.py
@dalthviz, I also added here a method called `save` to `NotebookClient` to save notebooks by clicking the *save* button in the notebook interface.
That will help you to finish issue #20 :-)
=> Add a widget to do DOM manipulations using Javascript

spyder_notebook/notebookplugin.py, spyder_notebook/widgets/client.py
=> PR: Shutdown kernel of the notebook before closing it

.ciocheck, circle.yml
Fixes #28 
For now only checks pep8 (but it does not enforce it), another PR will fix all formatting changes.
=> PR: Add CircleCI basic integration

setup.py, spyder_notebook/utils/nbopen.py, spyder_notebook/widgets/client.py
Fixes #12.
Without this we can't run our tests.
=> PR: Fixes to work with Notebook 4.3+

setup.py, spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/client.py
Fixes #45 
Preview:
___________________________________________
In order for this to work there is a need to modify the FileSwitcher class in spyder to map the correct methods to get the current widget (client).
The methods to change will be:
* `get_editor` (change the call for the `get_current_editor`)
* `save_initial_state` (let the current widget not have `textCursor`)
Also this works for now by adding a button to open the fileswitcher.
=> PR: Add a file switcher instance

setup.py, spyder_notebook/__init__.py, spyder_notebook/_version.py
Fixes #54
@ccordoba12 I move `__version__` to `_version.py` as you suggested
But that wasn't enough, when doing: `from spyder_notebook._version import __version__` the module is imported and the `__init__.py` is exectuted anyway
I copied a modified `get_version()` function from other spyder plugins, is that ok?
=> PR: Move version out of init file.

spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/client.py
=> PR: Add ellipsis to shorten notebook names

spyder_notebook/notebookplugin.py
=> PR: Add check_compatibility for PyQt4 and WebEngine

.github/ISSUE_TEMPLATE.md, README.md
=> PR: Add issue template and a link to the Spyder group for contact.

.circleci/install.sh, spyder_notebook/widgets/client.py, spyder_notebook/widgets/tests/test_client.py
Specifically, ignore sessions where the field for notebook path is not set. Also add tests for both the standard case and when the field is missing.
Fixes #153
=> PR: More robust parsing of server reply in NotebookClient.get_kernel_id()

.circleci/config.yml, .circleci/install.sh, spyder_notebook/notebookplugin.py, spyder_notebook/utils/nbopen.py, spyder_notebook/widgets/client.py
Update Spyder paths following the split-plugins merge, while maintaining compatibility with Spyder 3.
The plan is for spyder-notebook 0.1.x to be compatible with both Spyder 3 and Spyder 4, to allow for easy testing and development. To this end, this PR also changes one of the three CircleCI instances to test against Spyder's master branch. I expect that spyder-notebook 0.2.x will only support Spyder 4.
Fixes #158
=> PR: Update to Spyder 4 after the split-plugins merge

spyder_notebook/notebookplugin.py
The temp dir is now returned by a function instead of set by a global parameter.
Fixes #181
=> PR: Fix spyder4 import of TEMPDIR

.circleci/install.sh
For some reason, if we don't specify `qt=5` then Qt 4 is installed when we are installing `notebook` with Python 2, which causes the tests to fail.
Fixes #183
=> PR: Specify Qt 5 in CI test script

spyder_notebook/widgets/client.py, spyder_notebook/widgets/tests/test_client.py
Display a dialog box to the user if the HTTP request that this function makes, receives an error response or raises an exception due to a network error.
Fixes #192
Fixes #213
=> PR: Make .get_kernel_id() more robust

spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py
When the user closes a notebook tab, then the file name is checked to see whether the notebook was newly created (and thus stored in a temporary directory) and the notebook file is read to see whether the notebook contains anything. If both are the case, then the user is asked to save the notebook under a different name (and implicitly, in a permanent directory).
This PR reads the notebook file in this situation only if the file name indicates that the notebook was newly created. This is more efficient and it prevents errors when the user somehow opens a notebook file that does not exist. A regression test is added for the latter.
Fixes #187.
=> PR: Avoid reading notebook file when closing tab

spyder_notebook/notebookplugin.py
The name was changed in the base class in PR spyder-ide/spyder#9226.
Fixes #215 
Fixes #245
=> PR: Use _options_menu instead of options_menu in plugin

spyder_notebook/server/index.css, spyder_notebook/server/src/commands.ts, spyder_notebook/server/src/index.ts
This adds a menu bar to the rendered notebook and removes the side bar with the command palette. The menu bar is filled with items defined in the notebook component of Jupyter lab. 
Compared to Jupyter lab, the File, Tab, Settings and Help menus are missing. These are defined in other components so they are not so easy to include, and in many cases they require thought on how to integrate them properly in Spyder.
Fixes #270.
=> Add menu bar to notebook

.coveragerc, spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/utils/nbopen.py, spyder_notebook/widgets/client.py, spyder_notebook/widgets/example_app.py, spyder_notebook/widgets/notebooktabwidget.py
This PR splits the NotebookPlugin class in two parts: one part which handles the tabbed widget and one part responsible for integrating it into Spyder. There should not be any user visible changes.
I used the occasion to do some general clean up, including:
* Remove some functions that are not used.
* Remove some convenience functions that were only used in the tests.
* Add doc strings.
* Remove code specific to Python 2 or Spyder 3.
* Add a stand-alone app that can be used to view and edit notebooks.
Fixes #275
=> PR: Split off part of NotebookPlugin into NotebookTabWidget

spyder_notebook/utils/nbopen.py, spyder_notebook/utils/tests/test_nbopen.py, spyder_notebook/widgets/example_app.py
Currently, all notebook servers are killed. This PR uses the `shutdown_server()` function instead, which is gentler (though I am not sure it makes a difference).
Additionally, the PR converts `print()` to debug calls of the `logging` module and adds an (incomplete) test for `nbopen()`.
Fixes #171.
=> PR: Shutdown notebook server properly

spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/example_app.py, spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_notebooktabwidget.py
This PR makes Spyder store the file names of the notebooks that were open at the end of a session when the plugin is closed. The next time Spyder opens, the plugin will open these notebooks again. As before, notebooks with names like `untitled0.ipynb` in the temporary directory are deleted, so these will not be opened at the start of the next session. If there are no notebooks to be opened at the start of a session, the plugin will open a newly created notebook and display the welcome tab.
This PR also adds some tests and convenience functions for identifying the welcome tab and untitled, newly created notebooks. 
Fixes #68.
=> PR: Restore notebooks that were open at end of last session

spyder_notebook/notebookplugin.py, spyder_notebook/server/LICENSE, spyder_notebook/server/index.css, spyder_notebook/server/main.py, spyder_notebook/server/package.json, spyder_notebook/server/src/commands.ts, spyder_notebook/server/src/index.ts, spyder_notebook/tests/test_plugin.py, spyder_notebook/utils/nbopen.py, spyder_notebook/utils/templates/welcome-dark.html, spyder_notebook/widgets/example_app.py, spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_notebooktabwidget.py
This PR renders notebooks using the JupyerLab dark theme if the Spyder interface is set to dark.
It was not such a big change in the end but I learned a lot about JupyterLab, TypeScript and webpack in the process. You will see that the colour scheme of the JupyterLab dark theme is a bit different from Spyder: the text of the notebook pane is whiter and the background is blacker than in the other panes.
=> PR: Implement dark theme

spyder_notebook/server/src/commands.ts
This PR adds shortcuts like `M`, for changing the type of a cell to MarkDown. The list of added shortcuts is: Y, 1, 2, 3, 4, 5, 6, M, R, C, X, D D, Shift-ArrowUp, Shift-ArrowDown, A, B, V, Shift-Z, Ctrl-Enter, Alt-Enter, A A, Shift-L.
Fixes #306
=> PR: Add shortcuts that are available in Jupyter Lab

spyder_notebook/utils/servermanager.py
This PR fixes a compatibility issue with traitlets version 5. Older versions should still work.
Fixes #314
=> PR: Remove quotes from command line when starting server

spyder_notebook/widgets/client.py, spyder_notebook/widgets/tests/test_client.py
Having received the response from the server to our request to list all sessions, first check whether the status is ok and only if it is, parse the reply. Before (in code added in PR #232), this was done in the opposite order.
Update the test to ensure reply is not parsed if status is not ok.
Fixes #317.
=> PR: Check status when retrieving sessions before parsing reply

.github/workflows/linux-tests.yml, .github/workflows/macos-tests.yml, .github/workflows/windows-tests.yml
This replaces goanpeca/setup-miniconda which uses the deprecated add-path command.
=> PR: Use conda-incubator/setup-miniconda to install Miniconda

spyder_notebook/widgets/client.py, spyder_notebook/widgets/tests/test_client.py
A `NotebookClient` may not have a server registered with it (though it is unclear in what situations this occurs). This commit prevents `get_kernel_id()` from raising an exception in this case. It also adds a test.
Closes #311 
Closes #333
=> PR: Prevent AttributeError in get_kernel_id if no server

spyder_notebook/server/package.json, spyder_notebook/server/src/commands.ts, spyder_notebook/server/src/index.ts, spyder_notebook/server/src/tooltip.ts
Press Shift-Tab to access the tooltip (as in Jupyter Lab); see the below screenshot.
Fixes #315.
=> Add tooltips with help for Python functions

spyder_notebook/config.py, spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_config.py, spyder_notebook/tests/test_plugin.py
Add a Notebook config page, with a combo box to set the notebook theme. There are three possibilities: Dark, Light, Same as Spyder (default). Set the notebook theme according to the user's preference. Also add some tests.
Fixes #310
=> PR: Allow user to config notebook theme

spyder_notebook/widgets/notebooktabwidget.py
We no longer use `jupyter notebook` but added a menu item to check the output of the server process, so refer to that.
Fixes #337.
=> PR: Update error message when server times out

spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_notebooktabwidget.py
When saving a newly created notebook in a temporary directory, we read it back to check whether it is empty; if not, we offer to save it in a more permanent location. Before, we waited one second between initiating the save and reading it back. Now, we wait 0.25 second, but keep trying if the file does not yet exist. This means the function runs faster if the save is expedient and it waits longer if the save runs slowly.
The first commit in the PR is the one providing the functionality, the other commits are refactoring and adding tests.
Fixes #339.
=> PR: Wait a bit repeatedly after save before reading notebook

spyder_notebook/widgets/client.py
If the user does a right click in the notebook with Shift pressed down, then show Qt's standard context menu instead of our custom context menu, so that the user can copy or save images.
Fixes #279.
=> PR: Display standard Qt context menu on Shift-RightClick

spyder_notebook/widgets/client.py, spyder_notebook/widgets/tests/test_client.py
When the user clicks on a link in a notebook, the `NotebookWidget` calls `createWindow()` in order to open a new tab to display the link. This commit intercepts the call and creates a `WebViewInBrowser` object. When the URL in that object is set, the link is opened in an external web browser.
Fixes #185
=> PR: Display page in external browser when link in notebook is clicked

spyder_notebook/tests/test_plugin.py, spyder_notebook/utils/servermanager.py, spyder_notebook/utils/tests/test_servermanager.py, spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/serverinfo.py, spyder_notebook/widgets/tests/test_notebooktabwidget.py, spyder_notebook/widgets/tests/test_serverinfo.py
Record the Python interpreter selected in the Spyder preferences when a notebook server is started. When a new tab is opened, only use an existing server if it uses the interpreter that is set in the preferences when the tab is opened, otherwise start a new server which will use the current interpreter. The effect is that if the user changes the Python interpreter, new notebooks will use the new interpreter.
Also, update and add tests, and display the Python interpreter in the Server Info dialog window.
Fixes #266.
=> PR: Use interpreter preference when opening new tab

spyder_notebook/utils/templates/welcome-dark.html, spyder_notebook/utils/templates/welcome.html, spyder_notebook/widgets/client.py, spyder_notebook/widgets/main_widget.py
- Show border around `NotebookWidget`
- Improve welcome message a bit (make it simpler to read and update icons).
- Use Spyder main background color when creating new `NotebookWidget`'s.
This is how it looks now:
=> PR: Some style fixes so it looks better in Spyder 5

MANIFEST.in, README.md, RELEASE.md, setup.py
These are some small changes that are necessary before releasing version 0.4.0
=> PR: Fix building wheel and tarball with the latest `setuptools` version

spyder_notebook/server/main.py, spyder_notebook/utils/servermanager.py, spyder_notebook/utils/tests/test_servermanager.py, spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_serverinfo.py
Add a command line parameter to the notebook server for specifying the file in which connection information is to be stored. Use this parameter to set the file name to spynbserver-NNNN-MM.json where NNNN is the PID of the Spyder process and MM distinguishes between the notebook servers started by Spyder.
The reason for this is that Jupyter by default uses nbserver-XXXX.json where XXXX is the PID of the notebook server process, but in a venv in Windows there is no good method for finding this PID.
Fixes #398
=> PR: Specify file for storing connection info when starting server

codecov.yml, spyder_notebook/utils/templates/welcome-dark.html, spyder_notebook/utils/templates/welcome.html, spyder_notebook/widgets/main_widget.py
Also, add a reference to the 'Zoom in/out' menu items in the welcome tab.
Fixes #174 
Fixes #404
=> PR: Add New/Open Notebook items to notebook context menu

requirements/conda.txt, setup.py
Spyder version 5.4.3 includes PR spyder-ide/spyder#20482 which is needed on some Linux systems to display the notebooks.
Fixes #386.
=> PR: Require Spyder version 5.4.3

.github/workflows/run-tests.yml, conftest.py, spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/utils/servermanager.py, spyder_notebook/widgets/main_widget.py
This was quite simple, the main change is to adapt to the Switcher plugin.
Fixes #278.
=> PR: Update plugin to Spyder 6

spyder_notebook/notebookplugin.py, spyder_notebook/server/main.py, spyder_notebook/server/packages/application-extension/src/index.ts, spyder_notebook/utils/servermanager.py, spyder_notebook/utils/tests/test_servermanager.py
This fixes some functionality that was left out of the big PR #396: the Spyder prefs has a Notebook pane in which the user can choose to use the light or dark theme, but the notebook did not actually follow this setting.
The PR also fixes my typo in PR #417.
Fixes #402.
=> PR: Use Spyder prefs to set light/dark notebook theme

spyder_notebook/server/main.py
Specifically, this removes:
- menu item `View > Open JupyterLab`
- menu item `View > File Browser`
- menu item related to file editor in `Settings` menu
- menu item `Help > Launch Jupyter Notebook File Browser`
- toolbar button `Interface > Open With JupyterLab / Jupyter Notebook`
Fixes #400.
=> PR: Remove notebook menu items that do not work properly

spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_notebooktabwidget.py
This appears to be a rare error and its cause is not clear. The working assumption is that this exception may be raised if Spyder tries to read the notebook file before it is completely saved, so we wait a while and try again.
Fixes #432
=> PR: Catch NotJSONError in wait_and_check_if_empty()

.github/workflows/run-tests.yml, spyder_notebook/notebookplugin.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/main_widget.py
The 0.5.x branch of the plugin should be compatible with Spyder 5. Thus, we partially revert PR #417.
Fixes #423.
=> PR: Support Spyder 5 instead of Spyder 6

.github/scripts/generate-without-spyder.py, .github/workflows/run-tests.yml, requirements/conda.txt, spyder_notebook/tests/conftest.py, spyder_notebook/tests/test_config.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/client.py, spyder_notebook/widgets/main_widget.py, spyder_notebook/widgets/tests/test_main_widget.py
Two commits due to changes in Spyder API, change required version, and changes to make the tests run.
=>  PR: Compatibility fixes for Spyder 6.0.0 beta 1

spyder_notebook/notebookplugin.py
Specifically, make `NotebookPlugin.get_description()` a static method and `NotebookPlugin.get_icon()` a class method. This is required for Spyder 6.
Fixes #470.
=> PR: Add decorators to methods in NotebookPlugin

spyder_notebook/tests/test_config.py
Extend the test in `test_config.py` to check that the Plugins config page work. This would have caught the error in #470.
Having to call `set_all_internal_plugins()` explicitly makes the test a bit brittle but I don't see a better way to do this.
Fixes #472.
=> PR: Check that Plugins config page works with notebook plugin

setup.py
Python 3.12 removed the distutils module, and Python 3.13 removed the pipes module. Replace usage of both with either their documented replacements, or in the case of distutils, just use logging directly.
=> Support Python 3.12+ in setup.py

requirements/conda.txt, setup.py, spyder_notebook/server/main.py, spyder_notebook/utils/servermanager.py
Interrupting a kernel is done on Unix by sending SIGINT to the Python process. However, Spyder kernels use `conda run` to run the kernel in the correct environment. The SIGINT signal should not be sent to the `conda run` process, because that causes it to quit. Instead, find the Python process started by `conda run`, because it will handle SIGINT correctly by raising a KeyboardInterrupt.
This PR does some further clean up in the code for the notebook server because I now understand how to specify default configuration values instead of passing them on the command line.
Fixes #478
=> Fix interrupting Spyder kernel

spyder_notebook/server/main.py
If the user has installed other kernel specs, for instance for IPython kernels in other environments, and then changes kernel then all the kernel specs are shown with the same text (the display name of our own kernel spec). This is confusing.
This commit ensures that only one kernel spec is shown.
Fixes #475
=> Ensure that only one kernel spec is available

spyder_notebook/server/kernelspec.py, spyder_notebook/server/main.py
Do not explicitly import `SpyderKernelSpec` in `server/main.py`. Instead the traitlets mechanism will import it at instantiation time.
This gives a cleaner separation between the notebook server and Spyder. Practically, it prevents problems following from PR spyder-ide/spyder#24269.
=> PR: Defer import of SpyderKernelSpec

spyder_notebook/tests/test_plugin.py, spyder_notebook/widgets/tests/test_main_widget.py
Use the `@pytest.mark.flaky` marker in place of the `@flaky.flaky` decorator, to modernize the code and improve compatibility with other plugins providing the feature such as `pytest-rerunfailures`.
=> Replace `@flaky.flaky` decorate with pytest marker

.github/workflows/run-tests.yml, requirements/conda.txt, setup.py, spyder_notebook/config.py, spyder_notebook/notebookplugin.py, spyder_notebook/tests/conftest.py, spyder_notebook/tests/test_plugin.py, spyder_notebook/utils/templates/welcome-dark.html, spyder_notebook/utils/templates/welcome.html, spyder_notebook/widgets/main_widget.py, spyder_notebook/widgets/notebooktabwidget.py, spyder_notebook/widgets/tests/test_main_widget.py
This PR uses the hooks into the items in the File menu and the corresponding buttons in the toolbar that was added in PR spyder-ide/spyder#22564 so that they can be used to create, open, save and close notebooks. This requires Spyder 6.1, so change the lower version bound to that.
=> PR: Hook into file actions
