spyder-ide/spyder-notebook

README.md

Spelling Error Fix

---

.gitignore
README.md
spyder_notebook/__init__.py
spyder_notebook/notebookplugin.py
spyder_notebook/utils/__init__.py
spyder_notebook/utils/nbopen.py
spyder_notebook/widgets/__init__.py
spyder_notebook/widgets/client.py

This is a very (very!) crude implementation of the notebook running in Spyder.
Right now, it only creates empty notebooks in a dedicated plugin.

Initial implementation

---

spyder_notebook/notebookplugin.py

The plugin will be called *Jupyter Notebook* from now. Before we were adding the current file title to its name.

PR: Simplify plugin title

---

spyder_notebook/notebookplugin.py

This was giving an error in Preferences.

Don't try to set the widget fonts for now

---

spyder_notebook/utils/nbopen.py

A change in the max time to wait for the notebooks server to be up. See PR #16

PR: Change time to wait for the start of the server to max 10 secs.

---

spyder_notebook/widgets/client.py

PR: Fix [Errno 2] No such file or directory message

---

spyder_notebook/notebookplugin.py

PR: Add 'Options menu' and a way to move notebooks ('Save as…')

---

spyder_notebook/widgets/client.py

PR: Shorten notebook names with more than 15 characters

---

spyder_notebook/notebookplugin.py

Now we only show Jupyter notebooks as a filter.

Add a better filter to the "Save as" dialog

---

spyder_notebook/notebookplugin.py

PR: Add action to open notebooks from a file

---

spyder_notebook/notebookplugin.py

PR: Change the name of the action to 'New notebook' instead of 'Open a new notebook'

---

spyder_notebook/widgets/client.py
spyder_notebook/widgets/dom.py

PR: Add plugin actions to the 'NotebookWidget'

---

setup.py

PR: Add setup.py

---

spyder_notebook/notebookplugin.py

PR: Change the name of the plugin to 'Notebook'

---

setup.py

PR: Add Jupyter Trove classifier

---

circle.yml
spyder_notebook/tests/test_plugin.py
spyder_notebook/widgets/client.py
spyder_notebook/widgets/dom.py

PR: Hide the header of the notebook

---

spyder_notebook/utils/nbopen.py

PR: Add flag to not show cmd.exe windows on Windows

---

spyder_notebook/notebookplugin.py

PR: Set a new tempdir for untitled notebooks

---

spyder_notebook/notebookplugin.py

PR: Add save question for modified untitled notebooks before closing them

---

spyder_notebook/notebookplugin.py

PR: Add "Recent notebooks" menu entry

---

spyder_notebook/notebookplugin.py
spyder_notebook/tests/test_plugin.py
spyder_notebook/utils/nbopen.py

PR: Use Spyder kernel spec to create kernel notebooks

---

CHANGELOG.md
README.md
spyder_notebook/notebookplugin.py

This also doesn't forbid using this plugin with WebEngine, although that could change in the future.

PR: Improve Readme and Changelog

---

circle.yml
setup.py
spyder_notebook/utils/nbopen.py

Fixes #83.
@dalthviz, please test this one on Windows to see if it's working there too.

PR: Close servers when closing Spyder

---

RELEASE.md

PR: Add RELEASE.md file

---

spyder_notebook/notebookplugin.py
spyder_notebook/tests/test_plugin.py
spyder_notebook/utils/templates/welcome.html
spyder_notebook/utils/templates/welcome.md
spyder_notebook/widgets/client.py

PR: Add welcome message page

---

MANIFEST.in
setup.cfg
setup.py

Fixes #97 
Fixes #98 
Fixes #99 
Fixes #101

PR: Bugfixes after 0.1

---

spyder_notebook/notebookplugin.py

PR: Open a 'welcome' tab if there are no open tabs

---

spyder_notebook/notebookplugin.py

Fixes #121 
---------------------------------------
Edit:
~~This only will work with Spyder 4~~
It works with both Spyder 3.x and Spyder 4

PR: Change 'menu' for 'options_menu' for the new Spyder 4 undocking feature

---

spyder_notebook/utils/nbopen.py

PR: Increase time for server to start

---

README.md

Fixes #137 
--------------------
https://github.com/dalthviz/spyder-notebook/blob/f16c73bc0d5b170ed321acb8347d6fc71aba4c06/README.md

PR: Update README.md with Open collective info and missing badges.

---

spyder_notebook/tests/test_plugin.py

PR: Make tests use a temporary directory

---

spyder_notebook/notebookplugin.py
spyder_notebook/tests/test_plugin.py
spyder_notebook/widgets/client.py

Also add a test for this.
Fixes #152

PR: Display error when opening console for notebook with no kernel

---

spyder_notebook/notebookplugin.py
spyder_notebook/tests/test_plugin.py

Delete file when closing notebook if in temp dir

---

requirements/tests.txt
spyder_notebook/notebookplugin.py

PR: Set default for recent_notebooks config value

---

spyder_notebook/notebookplugin.py

This corrects PR #229 where I used the wrong type for `CONF_DEFAULTS` which for some reason still solved the underlying issue.

PR: Use correct type for CONF_DEFAULTS

---

README.md

PR: Update badges in README

---

setup.cfg
setup.py
spyder_notebook/notebookplugin.py
spyder_notebook/server/main.py
spyder_notebook/tests/test_plugin.py
spyder_notebook/widgets/client.py
spyder_notebook/widgets/dom.py

Require Python 3 and drop the code necessary to support Python 2.
Fixes #260.

PR: Drop support for Python 2

---

MANIFEST.in
requirements/conda.txt
requirements/tests.txt
setup.py
spyder_notebook/server/__init__.py
spyder_notebook/tests/__init__.py

This PR updates `setup.py` and related files so that the tar ball and the wheels include all the files needed to run the notebook server. It also updates the dependencies.
I used the code in spyder-terminal for inspiration.
Fixes #284
Fixes #296

PR: Install JavaScript files and other server components in distribution

---

spyder_notebook/server/src/index.ts

This PR makes code completions far more readable; compare the screenshot below with the one in the linked issue.
Fixes #318

PR: Import styles for completer

---

spyder_notebook/server/dark-theme-hack.css
spyder_notebook/server/src/index.ts

PR: Make colour of strings in notebook lighter

---

README.md

This is needed for https://github.com/spyder-ide/spyder/issues/15907.

PR: Add note to Readme to mention that this plugin doesn't work with our installers

---

.github/workflows/run-tests.yml
requirements/conda.txt
setup.py

* Use released version of Spyder 6 as requirement
* Test against both release version and current master in CI tests
* Bump required Python version to 3.8
Fixes #446 
Fixes #456 
By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.
I certify the above statement is true and correct:
Jitse Niesen

PR: Update to released version of Spyder 6

---

spyder_notebook/notebookplugin.py

Resolves the part of spyder-ide/spyder#21277 that pertains to this plugin.

Give focus to plugin when switching to it
